### ISSUE TITLE
Kestrel - System.InvalidOperationException: Status code cannot be set, response has already started.

### ISSUE THREAD

**Issue by pravinhabbu4u** [wesamco/ASP.Net-Core-GraphQL-Middleware#1]
Hello Wesam,

I was trying to utilize this solution to configure graphiql end point for .net core web application. We want to host this application using IIS on a windows server (any maybe linux in future). For now I am able to make it on my location machine but the same deployed on server is completing slowing down opening of /graphiql path. However, all other pages from website are opening fast. 

Are you aware of any such slowness issue?

**Comment by pravinhabbu4u** [comment]
I did some more research today and looks like fetch(window.location.origin + '@{GraphQLPath}', {
          method: 'post',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(graphQLParams),
          credentials: 'include',
        }) is failing when installed in IIS.

It is about the graphql end point not returning any outcome/ is not reachable as I getting:

GET http://localhost/graphiql net::ERR_CONNECTION_RESET

 graphiql:92 POST http://localhost/graphql 400 (Bad Request)

**Comment by pravinhabbu4u** [comment]
This issue is about .Kestrel server on:

        public async Task Invoke(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (ShouldRespondToRequest(context.Request))
            {

                await WriteResponseAsync(context.Response).ConfigureAwait(true);
            }
           
                await next(context).ConfigureAwait(true);
            
        }

**Comment by wis** [comment]
Hi @pravinhabbu4u 
[I suspect this is the bug fix](https://github.com/graphql-dotnet/graphql-dotnet/pull/175#discussion_r84987430)
will fix it later in this repo.

**Comment by pravinhabbu4u** [comment]
Thanks for the response @wesamco .
I did review the suspect page you have tagged above. However, I was still not able to pinpoint the actual error. Are you referring specificly to   response.StatusCode = executionResult.Errors?.Count == 0 ? 200 : 400;??

**Comment by wis** [comment]
@pravinhabbu4u Yes.

**Comment by pravinhabbu4u** [comment]
@wesamco 
I have fixed that portion but still I get runtime error on server as:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL2CF4C67PDU": An unhandled exception was thrown by the application.
System.InvalidOperationException: Status code cannot be set, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.<>c.<Build>b__16_0(HttpContext context)


This is happening in Graphiql middleware's Invoke method

        public async Task Invoke(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (ShouldRespondToRequest(context.Request))
            {
                await WriteResponseAsync(context.Response).ConfigureAwait(true);
            }
            
            await next(context).ConfigureAwait(true);
        }
I was looking for a way to change it the way it is done on GraphQLMiddleware's Invoke function.

Can you assist me with the same?

Kindly note this issue is only happening on windows server using IIS and not on my local machine using IIS Express.

**Comment by wis** [comment]
I have no idea, never run into that issue before, so Google is your best friend for that one, sorry.
but I guess on the server machine, you should check if the ports you are using for the web application are open.

**Comment by pravinhabbu4u** [comment]
@wesamco  Thanks for your response. This may be an issue with Kestrel server itself so I am trying to check on it. In the mean time I am planning to change the Invoke and WriteAsync response methods to see if this issue can be resolved. Thanks for all your time.

**Comment by pravinhabbu4u** [comment]
#https://github.com/wesamco/ASP.Net-Core-GraphQL-Middleware/issues/1

**Comment by pravinhabbu4u** [comment]
[https://github.com/wesamco/ASP.Net-Core-GraphQL-Middleware/issues/1](url)

**Comment by pravinhabbu4u** [comment]
[https://github.com/aspnet/HttpAbstractions/issues/686#issuecomment-277544623](url)

**Comment by pravinhabbu4u** [comment]
This issue is now resolved after adding return after writeasync in both Middleware servers.
