### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by claylaut** [wesamco/ASP.Net-Core-GraphQL-Middleware#3]
Hi,
Is this published on nuget? 
Thanks

**Comment by wis** [comment]
No, I think now [GraphQL-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) which is a dependency of this project, has ther own middle ware package.
if so I should deprecate this project.

**Comment by claylaut** [comment]
Thanks for your fast reply.

I've [opened an issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/444) maybe they will expose middleware extensions as you've done.
